// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ChessMoveValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("move")]
        public string Move { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("piece")]
        public string Piece { get; set; }

        [JsonProperty("capture")]
        public bool Capture { get; set; }

        [JsonProperty("check")]
        public bool Check { get; set; }

        [JsonProperty("checkmate")]
        public bool Checkmate { get; set; }

        [JsonProperty("promotion")]
        public bool Promotion { get; set; }
    }
}
